In [20]:
import pandas as pd
import numpy as np
data = { 
    "Name" : ["Suraj","Shree","Krish","Saquib","Om","Mohit","Raj","Hitesh","karan","Ram"],
    "Age" :[17,18,19,16,15,19,np.nan,22,23,24],
    "City" :["Nashik","Pune","Mumbai","Dubai","Nashik",np.nan,"New York","Brazil","Africa","Nashik"],
    "Marks":[90,20,45,79,89,23,45,34,np.nan,89]
}
df = pd.DataFrame(data)

In [21]:
df.isnull()

    Name    Age   City  Marks
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
5  False  False   True  False
6  False   True  False  False
7  False  False  False  False
8  False  False  False   True
9  False  False  False  False

In [22]:
df.isnull().sum()

Name     0
Age      1
City     1
Marks    1
dtype: int64

In [23]:
df.fillna("NULL")

     Name   Age      City Marks
0   Suraj  17.0    Nashik  90.0
1   Shree  18.0      Pune  20.0
2   Krish  19.0    Mumbai  45.0
3  Saquib  16.0     Dubai  79.0
4      Om  15.0    Nashik  89.0
5   Mohit  19.0      NULL  23.0
6     Raj  NULL  New York  45.0
7  Hitesh  22.0    Brazil  34.0
8   karan  23.0    Africa  NULL
9     Ram  24.0    Nashik  89.0

In [24]:
df["Age"].fillna(df["Age"].mean())

0    17.000000
1    18.000000
2    19.000000
3    16.000000
4    15.000000
5    19.000000
6    19.222222
7    22.000000
8    23.000000
9    24.000000
Name: Age, dtype: float64

In [25]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [26]:
df.drop_duplicates()

     Name   Age      City  Marks
0   Suraj  17.0    Nashik   90.0
1   Shree  18.0      Pune   20.0
2   Krish  19.0    Mumbai   45.0
3  Saquib  16.0     Dubai   79.0
4      Om  15.0    Nashik   89.0
5   Mohit  19.0       NaN   23.0
6     Raj   NaN  New York   45.0
7  Hitesh  22.0    Brazil   34.0
8   karan  23.0    Africa    NaN
9     Ram  24.0    Nashik   89.0

In [29]:
#permenent removal of duplicates 
df =df.drop_duplicates()

In [30]:
print(df)

     Name   Age      City  Marks
0   Suraj  17.0    Nashik   90.0
1   Shree  18.0      Pune   20.0
2   Krish  19.0    Mumbai   45.0
3  Saquib  16.0     Dubai   79.0
4      Om  15.0    Nashik   89.0
5   Mohit  19.0       NaN   23.0
6     Raj   NaN  New York   45.0
7  Hitesh  22.0    Brazil   34.0
8   karan  23.0    Africa    NaN
9     Ram  24.0    Nashik   89.0

In [ ]:
'''
Questions and answers 

Q1. What is Data Cleaning?
data cleaning is the process of cleaning unwanted data 

Q2. What is a Missing Value?
A missing value is a blank or NaN value in a dataset where data is not available.

Q3.Purpose of isnull()?  
It detects missing values and returns True/False.

Q4. Purpose of fillna()?
It is used to replace missing values with a specific value.

Q5. Difference between fillna() and dropna()?
fillna() is used to fill a specific value at the position of a null value
dropna() is used to drop means delete all the null values
'''