In [1]:
import pandas as pd
data = {
    "Student_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113],
    "Name": ["Raj", "Amit", "Priya", "Sneha", "Rahul", "Pooja", "Karan", "Neha", "Akash", "Komal", "Vikas", "Riya", "Raj"],
    "Age": [21, 22, 20, 23, 21, 22, 20, 21, 24, 23, None, 22, 21],
    "Gender": ["Male", "Male", "Female", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Male", "Female", "Male"],
    "City": ["Pune", "Mumbai", "Nashik", "Pune", "Mumbai", "Pune", "Nashik", "Pune", "Mumbai", "Pune", "Pune", "Mumbai", "Pune"],
    "Course": ["Python", "AI", "Python", "Data Science", "AI", "Python", "Data Science", "AI", "Python", "Data Science", "Python", "AI", "Python"],
    "Attendance": [90, 80, 95, 88, 75, 98, 82, 91, 85, 96, 90, None, 90],
    "Marks": [85, 75, 92, 81, 65, 96, 79, 89, 72, 94, None, 85, 85],
    "Purchased": ["Yes", "No", "Yes", "Yes", "No", "Yes", "No", "Yes", "No", "Yes", "Yes", "No", "Yes"]
}
df=pd.DataFrame(data)

In [2]:
print(df)

    Student_ID   Name   Age  Gender    City        Course  Attendance  Marks  \
0          101    Raj  21.0    Male    Pune        Python        90.0   85.0
1          102   Amit  22.0    Male  Mumbai            AI        80.0   75.0
2          103  Priya  20.0  Female  Nashik        Python        95.0   92.0
3          104  Sneha  23.0  Female    Pune  Data Science        88.0   81.0
4          105  Rahul  21.0    Male  Mumbai            AI        75.0   65.0
5          106  Pooja  22.0  Female    Pune        Python        98.0   96.0
6          107  Karan  20.0    Male  Nashik  Data Science        82.0   79.0
7          108   Neha  21.0  Female    Pune            AI        91.0   89.0
8          109  Akash  24.0    Male  Mumbai        Python        85.0   72.0
9          110  Komal  23.0  Female    Pune  Data Science        96.0   94.0
10         111  Vikas   NaN    Male    Pune        Python        90.0    NaN
11         112   Riya  22.0  Female  Mumbai            AI         NaN   85.0
12         113    Raj  21.0    Male    Pune        Python        90.0   85.0

   Purchased
0        Yes
1         No
2        Yes
3        Yes
4         No
5        Yes
6         No
7        Yes
8         No
9        Yes
10       Yes
11        No
12       Yes

In [3]:
df.head ()

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
0,101,Raj,21.0,Male,Pune,Python,90.0,85.0,Yes
1,102,Amit,22.0,Male,Mumbai,AI,80.0,75.0,No
2,103,Priya,20.0,Female,Nashik,Python,95.0,92.0,Yes
3,104,Sneha,23.0,Female,Pune,Data Science,88.0,81.0,Yes
4,105,Rahul,21.0,Male,Mumbai,AI,75.0,65.0,No

In [4]:
df.tail()

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
8,109,Akash,24.0,Male,Mumbai,Python,85.0,72.0,No
9,110,Komal,23.0,Female,Pune,Data Science,96.0,94.0,Yes
10,111,Vikas,NaN,Male,Pune,Python,90.0,NaN,Yes
11,112,Riya,22.0,Female,Mumbai,AI,NaN,85.0,No
12,113,Raj,21.0,Male,Pune,Python,90.0,85.0,Yes

In [7]:
df.shape

(13, 9)

In [8]:
df.columns

Index(['Student_ID', 'Name', 'Age', 'Gender', 'City', 'Course', 'Attendance',
       'Marks', 'Purchased'],
      dtype='str')

In [14]:
df.dtypes

Student_ID      int64
Name              str
Age           float64
Gender            str
City              str
Course            str
Attendance    float64
Marks         float64
Purchased         str
dtype: object

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  13 non-null     int64
 1   Name        13 non-null     str
 2   Age         12 non-null     float64
 3   Gender      13 non-null     str
 4   City        13 non-null     str
 5   Course      13 non-null     str
 6   Attendance  12 non-null     float64
 7   Marks       12 non-null     float64
 8   Purchased   13 non-null     str
dtypes: float64(3), int64(1), str(5)
memory usage: 1.0 KB

In [16]:
df.describe()

       Student_ID        Age  Attendance      Marks
count    13.00000  12.000000   12.000000  12.000000
mean    107.00000  21.666667   88.333333  83.166667
std       3.89444   1.230915    6.813534   9.281784
min     101.00000  20.000000   75.000000  65.000000
25%     104.00000  21.000000   84.250000  78.000000
50%     107.00000  21.500000   90.000000  85.000000
75%     110.00000  22.250000   92.000000  89.750000
max     113.00000  24.000000   98.000000  96.000000

In [19]:
df.isnull()

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,True,False,False,False,False,True,False
11,False,False,False,False,False,False,True,False,False
12,False,False,False,False,False,False,False,False,False

In [20]:
df.isnull().sum()

Student_ID    0
Name          0
Age           1
Gender        0
City          0
Course        0
Attendance    1
Marks         1
Purchased     0
dtype: int64

In [22]:
df["Age"]=df["Age"].fillna(df["Age"].mean())

In [24]:
df["Marks"]=df["Marks"].fillna(df["Marks"].mean())

In [29]:
df["Attendance"]=df["Attendance"].fillna(df["Attendance"].mean())

In [30]:
df.isnull().sum()

Student_ID    0
Name          0
Age           0
Gender        0
City          0
Course        0
Attendance    0
Marks         0
Purchased     0
dtype: int64

In [34]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
dtype: bool

In [35]:
df.duplicated().sum()

np.int64(0)

In [37]:
df= df.drop_duplicates()

In [38]:
#data selection
df["Name"]

0       Raj
1      Amit
2     Priya
3     Sneha
4     Rahul
5     Pooja
6     Karan
7      Neha
8     Akash
9     Komal
10    Vikas
11     Riya
12      Raj
Name: Name, dtype: str

In [41]:
df[df["Attendance"]>75]

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
0,101,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes
1,102,Amit,22.000000,Male,Mumbai,AI,80.000000,75.000000,No
2,103,Priya,20.000000,Female,Nashik,Python,95.000000,92.000000,Yes
3,104,Sneha,23.000000,Female,Pune,Data Science,88.000000,81.000000,Yes
5,106,Pooja,22.000000,Female,Pune,Python,98.000000,96.000000,Yes
6,107,Karan,20.000000,Male,Nashik,Data Science,82.000000,79.000000,No
7,108,Neha,21.000000,Female,Pune,AI,91.000000,89.000000,Yes
8,109,Akash,24.000000,Male,Mumbai,Python,85.000000,72.000000,No
9,110,Komal,23.000000,Female,Pune,Data Science,96.000000,94.000000,Yes
10,111,Vikas,21.666667,Male,Pune,Python,90.000000,83.166667,Yes
11,112,Riya,22.000000,Female,Mumbai,AI,88.333333,85.000000,No
12,113,Raj,21.000000,Male,Pune,Python,90.000000,85.000000,Yes

In [40]:
df[["Name", "City", "Course"]]

     Name    City        Course
0     Raj    Pune        Python
1    Amit  Mumbai            AI
2   Priya  Nashik        Python
3   Sneha    Pune  Data Science
4   Rahul  Mumbai            AI
5   Pooja    Pune        Python
6   Karan  Nashik  Data Science
7    Neha    Pune            AI
8   Akash  Mumbai        Python
9   Komal    Pune  Data Science
10  Vikas    Pune        Python
11   Riya  Mumbai            AI
12    Raj    Pune        Python

In [42]:
df[df["City"]=="Mumbai"]

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
1,102,Amit,22.0,Male,Mumbai,AI,80.000000,75.0,No
4,105,Rahul,21.0,Male,Mumbai,AI,75.000000,65.0,No
8,109,Akash,24.0,Male,Mumbai,Python,85.000000,72.0,No
11,112,Riya,22.0,Female,Mumbai,AI,88.333333,85.0,No

In [43]:
df[(df["Gender"] == "Male") & (df["City"] == "Pune")]

,Student_ID,Name,Age,Gender,City,Course,Attendance,Marks,Purchased
0,101,Raj,21.000000,Male,Pune,Python,90.0,85.000000,Yes
10,111,Vikas,21.666667,Male,Pune,Python,90.0,83.166667,Yes
12,113,Raj,21.000000,Male,Pune,Python,90.0,85.000000,Yes

In [44]:
df["City"].unique()

<StringArray>
['Pune', 'Mumbai', 'Nashik']
Length: 3, dtype: str

In [46]:
df["Course"].unique()

<StringArray>
['Python', 'AI', 'Data Science']
Length: 3, dtype: str

In [47]:
df.groupby("City")["Marks"].mean()

City
Mumbai    74.250000
Nashik    85.500000
Pune      87.595238
Name: Marks, dtype: float64

In [48]:
df.groupby("Course")["Marks"].max()

Course
AI              89.0
Data Science    94.0
Python          96.0
Name: Marks, dtype: float64

In [49]:
df.groupby("City")["Attendance"].mean()

City
Mumbai    82.083333
Nashik    88.500000
Pune      91.857143
Name: Attendance, dtype: float64

In [52]:
df.groupby("Course")["Marks"].agg(["max","min","sum","mean"])

               max   min         sum       mean
Course
AI            89.0  65.0  314.000000  78.500000
Data Science  94.0  79.0  254.000000  84.666667
Python        96.0  72.0  513.166667  85.527778

In [53]:
df.corr(numeric_only=True)

            Student_ID       Age  Attendance     Marks
Student_ID    1.000000  0.211830    0.192436  0.146079
Age           0.211830  1.000000    0.073467 -0.114050
Attendance    0.192436  0.073467    1.000000  0.952015
Marks         0.146079 -0.114050    0.952015  1.000000

In [54]:
df["Gender"] = df["Gender"].map({"Male": 1, "Female": 0})
df["Purchased"] = df["Purchased"].map({"Yes": 1, "No": 0})

In [55]:
df = pd.get_dummies(df, columns=["City", "Course"])

In [62]:
X = df[["Marks","Age","Attendance"]]

In [64]:
Y= df["Purchased"]

In [65]:
df.to_csv("cleaned_student_performance.csv", index=False)